### PR TITLE
Enhancements: Server - side

### PR DESCRIPTION
**Pull request by Criticalcarpet**
Added : 
- `.gitignore` file
- `.env.example` file
- `nanoid` package
- `dotenv` package

Changed : 
- `create.ejs` to facilitate POST request to `/create` endpoint
- `index.js` to facilitate the new package for id generation and minor best practices
- `package.json` to convert the project to ES 6 for better security
- `model.js` to improvise imports and exports

### CODE REVIEW

**Comment by Criticalcarpet** [comment]
There are a few more things to fix, I will start working on them when this PR is merged successfully.
Thank you.

Best regards,
Criticalcarpet

**Comment by Rahuletto** [comment]
I have some doubts about the commit

- Why do we need a POST request at save when the form also does the same thing ?

- Why do we need to rely on packages/modules to make an ID string ?

**Comment by Criticalcarpet** [comment]
@Rahuletto 

> * Why do we need a POST request at save when the form also does the same thing ?

There is the `method` mentioned but the `action` attribute is not mentioned.
Also doing things with js is more user-friendly and controllable 

> * Why do we need to rely on packages/modules to make an ID string ?

Previously there was a normal function being used which had a higher chances of collision and cryptographically not safe.
As per best-practices, certified modules can be used to generate unique IDs.
I thought of going with `uuid` but `nanoid` was faster and was able to generate shorter Ids

**Comment by Criticalcarpet** [comment]
Please let me know if I can open an another PR with some more enhancements.
enhancements include : 
- A test suite(cypress)
- Linter(eslint)
- separate js files in the front-end
- fix `view bin` err while viewing the created bin

**Comment by Rahuletto** [comment]
Can u explain the `view bin` error a bit more ?

**Comment by Criticalcarpet** [comment]
> Can u explain the `view bin` error a bit more ?

There is an error being thrown in the client-side browser console when visiting a created bin: 
```js
Uncaught TypeError: Cannot read properties of null (reading 'value')
    at Function.fromTextArea (codemirror.js:9715:30)
    at lktL186KIVLM:62:25
```

This also results to absence of the code contained in the bin but the title and misc details appear

**Pull request merged**
